# Generated by Django 4.0.5 on 2022-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentariocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('update', models.DateTimeField(auto_created=True, verbose_name='Actualizacion')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-create'],
            },
        ),
    ]
