# Generated by Django 4.0.5 on 2022-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Actualizacion'),
        ),
    ]
